// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signup-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request data to create new todo task
type CreateSignupRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Task entity to add
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupRequest) Reset()         { *m = CreateSignupRequest{} }
func (m *CreateSignupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSignupRequest) ProtoMessage()    {}
func (*CreateSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931065e041907290, []int{0}
}

func (m *CreateSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupRequest.Unmarshal(m, b)
}
func (m *CreateSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupRequest.Marshal(b, m, deterministic)
}
func (m *CreateSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupRequest.Merge(m, src)
}
func (m *CreateSignupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSignupRequest.Size(m)
}
func (m *CreateSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupRequest proto.InternalMessageInfo

func (m *CreateSignupRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateSignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Contains data of created todo task
type CreateSignupResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// UUID of created signup
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupResponse) Reset()         { *m = CreateSignupResponse{} }
func (m *CreateSignupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSignupResponse) ProtoMessage()    {}
func (*CreateSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931065e041907290, []int{1}
}

func (m *CreateSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupResponse.Unmarshal(m, b)
}
func (m *CreateSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupResponse.Marshal(b, m, deterministic)
}
func (m *CreateSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupResponse.Merge(m, src)
}
func (m *CreateSignupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSignupResponse.Size(m)
}
func (m *CreateSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupResponse proto.InternalMessageInfo

func (m *CreateSignupResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSignupRequest)(nil), "v1.CreateSignupRequest")
	proto.RegisterType((*CreateSignupResponse)(nil), "v1.CreateSignupResponse")
}

func init() { proto.RegisterFile("signup-service.proto", fileDescriptor_931065e041907290) }

var fileDescriptor_931065e041907290 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0xb6, 0x5b, 0xc0, 0xac, 0xa0, 0x32, 0x45, 0x44, 0x11, 0x07, 0x13, 0x71, 0x40,
	0x15, 0x8d, 0xdb, 0xd2, 0x53, 0xe1, 0x00, 0xec, 0x9d, 0x43, 0x96, 0x3b, 0xf2, 0x26, 0x83, 0xeb,
	0x25, 0xb1, 0x8d, 0xc7, 0x49, 0x01, 0x71, 0xe2, 0x11, 0xe0, 0xc6, 0x6b, 0xed, 0x81, 0x17, 0xe0,
	0x41, 0x50, 0xed, 0x5d, 0xa4, 0x55, 0xf7, 0x94, 0x99, 0xf9, 0xbf, 0xf8, 0x97, 0xff, 0x31, 0x99,
	0xa2, 0x92, 0xba, 0xb3, 0x73, 0x04, 0xd7, 0xab, 0x0a, 0x0a, 0xeb, 0x8c, 0x37, 0x74, 0xd0, 0x2f,
	0xb3, 0xc7, 0xd2, 0x18, 0xd9, 0x00, 0x17, 0x56, 0x71, 0xa1, 0xb5, 0xf1, 0xc2, 0x2b, 0xa3, 0x31,
	0x12, 0xd9, 0xf3, 0xf0, 0xa9, 0xe6, 0x12, 0xf4, 0x1c, 0x77, 0x42, 0x4a, 0x70, 0xdc, 0xd8, 0x40,
	0x1c, 0xd2, 0xf9, 0x77, 0xf2, 0xe0, 0xc4, 0x81, 0xf0, 0x70, 0x1a, 0xdc, 0x4a, 0xf8, 0xdc, 0x01,
	0x7a, 0x3a, 0x21, 0x43, 0x61, 0x55, 0x9a, 0xb0, 0xe4, 0xd9, 0x9d, 0x72, 0x5f, 0xd2, 0x27, 0xe4,
	0xb8, 0x56, 0x68, 0x1b, 0xf1, 0xf5, 0x83, 0x16, 0x2d, 0xa4, 0x83, 0x20, 0xdd, 0xbd, 0x9c, 0xbd,
	0x13, 0x2d, 0xd0, 0x29, 0x39, 0x82, 0x56, 0xa8, 0x26, 0x1d, 0x06, 0x2d, 0x36, 0x34, 0x23, 0xb7,
	0xad, 0x40, 0xdc, 0x19, 0x57, 0xa7, 0xa3, 0x20, 0xfc, 0xef, 0xf3, 0x57, 0x64, 0x7a, 0xdd, 0x1d,
	0xad, 0xd1, 0x08, 0x37, 0xd8, 0x53, 0x32, 0xea, 0x3a, 0x55, 0x07, 0xdb, 0xe3, 0x32, 0xd4, 0xab,
	0x8f, 0x64, 0x12, 0xff, 0x3b, 0x69, 0xeb, 0xd3, 0x98, 0x12, 0x2d, 0xc9, 0x38, 0x9e, 0x48, 0x1f,
	0x15, 0xfd, 0xb2, 0xb8, 0xe1, 0x6e, 0x59, 0x7a, 0x28, 0x44, 0xdb, 0xfc, 0xe1, 0x8f, 0x8b, 0xbf,
	0xbf, 0x06, 0xf7, 0x73, 0xc2, 0xfb, 0x25, 0x8f, 0xf1, 0x6f, 0x92, 0xd9, 0xdb, 0x3f, 0xc9, 0xcf,
	0x37, 0x17, 0x09, 0x6d, 0xc9, 0xbd, 0xc8, 0xb3, 0xcb, 0x95, 0xe4, 0xef, 0xc9, 0x44, 0x3a, 0x5b,
	0xcd, 0x85, 0x55, 0xcc, 0x3a, 0x73, 0x0e, 0x95, 0xa7, 0x4f, 0xb7, 0xde, 0x5b, 0xdc, 0x70, 0x2e,
	0x95, 0xdf, 0x76, 0x67, 0x45, 0x65, 0x5a, 0x5e, 0x7f, 0x53, 0xda, 0x0b, 0x87, 0xfc, 0x8a, 0xce,
	0xb2, 0xab, 0x51, 0xf1, 0xa9, 0x11, 0xbd, 0xd2, 0xf8, 0x5a, 0xee, 0xc3, 0xda, 0xd3, 0xab, 0xa3,
	0x45, 0xb1, 0x28, 0x96, 0xb3, 0x24, 0x59, 0x4d, 0x84, 0xb5, 0x8d, 0xaa, 0xc2, 0xc2, 0xf8, 0x39,
	0x1a, 0xbd, 0x39, 0x98, 0x94, 0x2f, 0xc9, 0x70, 0xbd, 0x58, 0xd3, 0x35, 0x99, 0x95, 0xe0, 0x3b,
	0xa7, 0xa1, 0x66, 0xbb, 0x2d, 0x68, 0xe6, 0xb7, 0xc0, 0x1c, 0xa0, 0xe9, 0x5c, 0x05, 0xac, 0x36,
	0x80, 0x4c, 0x1b, 0xcf, 0xe0, 0x8b, 0x42, 0x5f, 0xd0, 0x31, 0x19, 0xfd, 0x1e, 0x24, 0xb7, 0xce,
	0xc6, 0xe1, 0x11, 0xbc, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x1a, 0x2e, 0x33, 0x6c, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupCmdServiceClient is the client API for SignupCmdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupCmdServiceClient interface {
	// Create new todo task
	Create(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error)
}

type signupCmdServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupCmdServiceClient(cc *grpc.ClientConn) SignupCmdServiceClient {
	return &signupCmdServiceClient{cc}
}

func (c *signupCmdServiceClient) Create(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error) {
	out := new(CreateSignupResponse)
	err := c.cc.Invoke(ctx, "/v1.SignupCmdService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupCmdServiceServer is the server API for SignupCmdService service.
type SignupCmdServiceServer interface {
	// Create new todo task
	Create(context.Context, *CreateSignupRequest) (*CreateSignupResponse, error)
}

func RegisterSignupCmdServiceServer(s *grpc.Server, srv SignupCmdServiceServer) {
	s.RegisterService(&_SignupCmdService_serviceDesc, srv)
}

func _SignupCmdService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupCmdServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SignupCmdService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupCmdServiceServer).Create(ctx, req.(*CreateSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupCmdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SignupCmdService",
	HandlerType: (*SignupCmdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SignupCmdService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signup-service.proto",
}
